-- USING PGADMIN GUI : CREATE A DATABASE mydata
-- USING PGADMIN GUI : CREATE A TABLE accounts

SELECT * FROM accounts;

-- USING PGADMIN GUI : VIEW TABLE STRUCTURE
-- USING PGADMIN GUI : CREATE A COLUMN 
-- USING PGADMIN GUI : RENAME A COLUMN 
-- USING PGADMIN GUI : DROP / DELETE A COLUMN
-- USING PGADMIN GUI : CHANGE DATA TYPE OF A COLUMN


-- DELETING TABLES FROM A DATABASE
CREATE TABLE roles (
	role_id SERIAL PRIMARY KEY,
	role_name VARCHAR(100)
);

SELECT * FROM roles;

-- USING PGADMIN GUI : DELETE A TABLE

DROP TABLE IF EXISTS roles;